# Generated by Django 4.1.1 on 2022-10-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='school.student'),
        ),
        migrations.AlterField(
            model_name='studentteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='school.teacher'),
        ),
    ]
